name: Build and Publish Library

on:
  push:
    branches: [ main ]
    tags:
      - 'V-*'
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  test:
    name: 🧪 Run Tests
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - run: chmod +x gradlew

      - name: Run Unit Tests
        run: ./gradlew :location-tracker:allTests

  build:
    name: 🔨 Build Library
    runs-on: macos-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - run: chmod +x gradlew

      - name: Build Android & iOS Artifacts
        run: ./gradlew :location-tracker:assemble

  publish:
    name: 🚀 Publish GitHub Packages
    runs-on: macos-latest
    needs: build

    if: startsWith(github.ref, 'refs/tags/V-')

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - run: chmod +x gradlew

      - name: Publish
        run: ./gradlew :location-tracker:publishAllPublicationsToGitHubPackagesRepository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPR_USER: ${{ github.actor }}
          GPR_TOKEN: ${{ secrets.GITHUB_TOKEN }}